# Generated by Django 2.0 on 2017-12-13 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('name', models.CharField(max_length=100)),
                ('food_type', models.CharField(choices=[('Snack', 'Snack'), ('Drink', 'Drink'), ('Entree', 'Entree'), ('Side', 'Side'), ('Dessert', 'Dessert')], max_length=7)),
                ('total_servings', models.PositiveSmallIntegerField()),
                ('uri', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_recipe', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.PositiveSmallIntegerField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_manager.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='StagedMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('num', models.PositiveSmallIntegerField()),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=9)),
                ('meal_time', models.TimeField(blank=True, null=True)),
                ('items', models.ManyToManyField(through='food_manager.SetCourse', to='food_manager.FoodItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='setcourse',
            name='staged_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_manager.StagedMeal'),
        ),
    ]
