# Generated by Django 2.0 on 2017-12-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedmeal',
            name='day',
            field=models.CharField(choices=[('DEF', 'Default'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='DEF', max_length=3),
        ),
    ]
