# Generated by Django 2.0 on 2017-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_manager', '0002_auto_20171214_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stagedmeal',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stagedmeal',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stagedmeal',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stagedmeal',
            name='num',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='stagedmeal',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
    ]
