# Generated by Django 2.0 on 2017-12-15 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CURL', 'Bicep Curl'), ('PULL', 'Pull-up'), ('PRESS', 'Shoulder Press'), ('ROW', 'Bent Over Row'), ('RAISE', 'Calf Raises'), ('SQUAT', 'Back Squat'), ('BENCH', 'Bench Press'), ('DEADS', 'Deadlift'), ('EXTEN', 'Tricep Extension')], default='BENCH', max_length=5)),
                ('load', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('rest', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SIX', '6'), ('TWO', '2'), ('FOU', '4'), ('SEV', '7'), ('FIV', '5'), ('DEF', 'Default'), ('ONE', '1'), ('THR', '3')], default='DEF', max_length=3)),
                ('workout_name', models.CharField(max_length=40)),
                ('sets', models.ManyToManyField(to='workout_manager.Set')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(default='workout', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutprofiles', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ManyToManyField(to='workout_manager.Workout')),
            ],
        ),
    ]
