# Generated by Django 2.0 on 2017-12-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(choices=[('ROW', 'Bent Over Row'), ('BENCH', 'Bench Press'), ('SQUAT', 'Back Squat'), ('CURL', 'Bicep Curl'), ('EXTEN', 'Tricep Extension'), ('PRESS', 'Shoulder Press'), ('DEADS', 'Deadlift'), ('RAISE', 'Calf Raises'), ('PULL', 'Pull-up')], default='BENCH', max_length=5),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(choices=[('ONE', '1'), ('FIV', '5'), ('THR', '3'), ('SIX', '6'), ('DEF', 'Default'), ('TWO', '2'), ('FOU', '4'), ('SEV', '7')], default='DEF', max_length=3),
        ),
    ]
