# Generated by Django 2.0 on 2017-12-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0002_auto_20171215_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutprofile',
            old_name='type',
            new_name='data_type',
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(choices=[('CURL', 'Bicep Curl'), ('SQUAT', 'Back Squat'), ('BENCH', 'Bench Press'), ('PULL', 'Pull-up'), ('RAISE', 'Calf Raises'), ('PRESS', 'Shoulder Press'), ('ROW', 'Bent Over Row'), ('DEADS', 'Deadlift'), ('EXTEN', 'Tricep Extension')], default='BENCH', max_length=5),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(choices=[('SIX', '6'), ('FOU', '4'), ('ONE', '1'), ('SEV', '7'), ('THR', '3'), ('TWO', '2'), ('DEF', 'Default'), ('FIV', '5')], default='DEF', max_length=3),
        ),
    ]
