# Generated by Django 2.0 on 2017-12-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0003_auto_20171215_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(choices=[('ROW', 'Bent Over Row'), ('PULL', 'Pull-up'), ('CURL', 'Bicep Curl'), ('DEADS', 'Deadlift'), ('EXTEN', 'Tricep Extension'), ('PRESS', 'Shoulder Press'), ('BENCH', 'Bench Press'), ('SQUAT', 'Back Squat'), ('RAISE', 'Calf Raises')], default='BENCH', max_length=5),
        ),
        migrations.AlterField(
            model_name='set',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(choices=[('TWO', '2'), ('ONE', '1'), ('THR', '3'), ('SIX', '6'), ('DEF', 'Default'), ('SEV', '7'), ('FOU', '4'), ('FIV', '5')], default='DEF', max_length=3),
        ),
    ]
