# Generated by Django 2.0 on 2017-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0004_auto_20171215_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(choices=[('ROW', 'Bent Over Row'), ('BENCH', 'Bench Press'), ('PRESS', 'Shoulder Press'), ('PULL', 'Pull-up'), ('DEADS', 'Deadlift'), ('SQUAT', 'Back Squat'), ('CURL', 'Bicep Curl'), ('RAISE', 'Calf Raises'), ('EXTEN', 'Tricep Extension')], default='BENCH', max_length=5),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(choices=[('FIV', '5'), ('FOU', '4'), ('DEF', 'Default'), ('SEV', '7'), ('SIX', '6'), ('THR', '3'), ('TWO', '2'), ('ONE', '1')], default='DEF', max_length=3),
        ),
    ]
